### ISSUE TITLE
main.batが正しく実行できない

### ISSUE THREAD

**Issue by fvh-P** [pulcherriman/cmd_Mahjong#1]
main.batを実行すると
`1!!_d! の使い方が誤っています。`
と表示される。

https://github.com/pulcherriman/cmd_Mahjong/blob/9a1772ffa8b8bd1dc2e0626741cce37a1702e7b2/Utility/shipai.bat#L6

この行が悪い？

**Comment by pulcherriman** [comment]
解決しました。
